# Generated by Django 5.2.4 on 2026-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0078_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Email verification'), ('password_reset', 'Password reset'), ('account_reactivation', 'Account reactivation'), ('account_delete', 'Account delete')], default='email_verify', max_length=32),
        ),
    ]
