# Generated by Django 5.2.4 on 2026-07-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0079_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='propertylist_app.room'),
        ),
    ]
