
# Generated by Django 5.2.4 on 2026-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0080_messagethread_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
