# Generated by Django 5.2.4 on 2026-07-19 18:59

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_review_notifications(apps, schema_editor):
    Notification = apps.get_model("propertylist_app", "Notification")

    review_notifications = Notification.objects.filter(
        type="review_available",
        target_type="tenancy_review",
        target_id__isnull=False,
    )

    duplicate_groups = (
        review_notifications
        .values("user_id", "type", "target_type", "target_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )

    for group in duplicate_groups.iterator():
        matching_notifications = review_notifications.filter(
            user_id=group["user_id"],
            type=group["type"],
            target_type=group["target_type"],
            target_id=group["target_id"],
        ).order_by("created_at", "id")

        keep_id = matching_notifications.values_list(
            "id",
            flat=True,
        ).first()

        if keep_id is not None:
            matching_notifications.exclude(id=keep_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("propertylist_app", "0083_userprofile_identity_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_review_notifications,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    target_id__isnull=False,
                    target_type="tenancy_review",
                    type="review_available",
                ),
                fields=("user", "type", "target_type", "target_id"),
                name="uq_notification_review_per_user_tenancy",
            ),
        ),
    ]