# Generated by Django 5.2.4 on 2026-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0084_notification_uq_notification_review_per_user_tenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/previews/'),
        ),
    ]
