# Generated by Django 5.2.4 on 2026-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0085_roomimage_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='moderation_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='moderation_notes',
            field=models.TextField(blank=True, default='', help_text='Internal moderation result or provider error details.'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='moderation_reason',
            field=models.CharField(choices=[('awaiting_check', 'Awaiting automated check'), ('auto_approved', 'Automatically approved'), ('manual_review', 'Manual review'), ('unsafe_content', 'Unsafe content detected'), ('not_property_photo', 'Not a property photo'), ('low_confidence', 'Low moderation confidence'), ('timeout', 'Moderation service timeout'), ('service_unavailable', 'Moderation service unavailable'), ('validation_failed', 'Basic image validation failed')], db_index=True, default='awaiting_check', max_length=32),
        ),
    ]
