# Generated by Django 5.2.4 on 2026-07-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0086_roomimage_moderation_checked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='preview_image',
        ),
    ]
