# Generated by Django 5.2.4 on 2026-07-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0087_remove_roomimage_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_monthly_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_payment_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_system_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_user_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_weekly_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_timezone',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('system', 'System default'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_format',
            field=models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='24h', max_length=3),
        ),
    ]
