# Generated by Django 5.2.4 on 2026-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0088_userprofile_date_format_userprofile_notify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('tenancy_proposal', 'Tenancy proposal'), ('tenancy_updated', 'Tenancy updated'), ('tenancy_confirmed', 'Tenancy confirmed'), ('tenancy_cancelled', 'Tenancy cancelled')], db_index=True, default='text', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
