# Generated by Django 5.2.4 on 2026-08-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "propertylist_app",
            "0089_message_message_type_message_metadata",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="cover_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="User-selected cover photo for this room.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_for_rooms",
                to="propertylist_app.roomimage",
            ),
        ),
    ]