# Generated by Django 5.2.4 on 2026-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "propertylist_app",
            "0090_room_cover_photo",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenancyextension",
            name="proposed_start_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),
    ]