# Generated by Django 5.2.4 on 2026-08-28 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0092_user_email_case_insensitive_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='landlord',
            field=models.ForeignKey(blank=True, help_text='Landlord-side participant snapshotted for role-scoped messaging.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='seeker',
            field=models.ForeignKey(blank=True, help_text='Seeker-side participant snapshotted for role-scoped messaging.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeker_message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('seeker', 'Seeker'), ('both', 'Both')], db_index=True, default='both', max_length=16),
        ),
    ]
